language: generic
services: 
  - docker

before_script:
  - docker build -t $DOCKER_LATEST .

script:
  - docker tag $DOCKER_LATEST $DOCKER_VERSION

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $DOCKER_LATEST && docker push $DOCKER_VERSION
  on:
    branch: 
      - master