language: generic
services: 
  - docker

before_script:
  - docker build -t $DOCKER_IMAGE:$DOCKER_VERSION .

script:
  - docker tag $DOCKER_IMAGE:$DOCKER_VERSION $DOCKER_IMAGE:latest

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $DOCKER_IMAGE:$DOCKER_VERSION && docker push $DOCKER_IMAGE:latest
  on:
    branch: 
      - master