language: generic
services: 
  - docker

before_script:
  - docker build -t $DOCKER_IMAGE:$DOCKER_VERSION .

script:
  - 'if [ "$DOCKER_LATEST" == "true" ]; then docker tag $DOCKER_IMAGE:$DOCKER_VERSION $DOCKER_IMAGE:latest; fi'

deploy:
  provider: script
  script: 
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - docker push $DOCKER_IMAGE:$DOCKER_VERSION
    - 'if [ "$DOCKER_LATEST" == "true" ]; then docker push $DOCKER_IMAGE:latest; fi'
  on:
    branch: 
      - master